"""Multi-page wiki compile: LLM JSON to wiki/concepts/ and meta/wiki_index.json."""

from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, cast

from openai import OpenAI

from crate.compile_run import CompileResult, build_compile_prompt
from crate.compile_state import fingerprints_for_paths, merge_save_raw_fingerprints
from crate.llm import (
    DeepSeekConfig,
    build_openai_client,
    chat_extra_kwargs_for_purpose,
    load_deepseek_config,
    truncate_prompt_for_purpose,
)
from crate.vault_paths import VaultContext

WIKI_INDEX_FILENAME = "wiki_index.json"
COMPILE_WIKI_LAST_FILENAME = "compile_wiki_last.json"

__all__ = [
    "run_wiki_graph_compile",
    "sanitize_slug",
    "extract_json_object",
    "COMPILE_WIKI_LAST_FILENAME",
]


def sanitize_slug(raw: str) -> str:
    """ASCII slug safe for filenames; empty -> ``concept``."""
    s = raw.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = s.strip("-")[:80]
    return s or "concept"


def extract_json_object(text: str) -> dict[str, Any]:
    """Parse JSON from model output (raw or fenced)."""
    t = text.strip()
    fence = re.search(r"```(?:json)?\s*([\s\S]*?)```", t)
    if fence:
        t = fence.group(1).strip()
    data = json.loads(t)
    if not isinstance(data, dict):
        raise ValueError("expected JSON object at top level")
    return cast(dict[str, Any], data)


def _prompt_file_path() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "prompts" / "wiki_multi.md"


def _render_backlinks_md(
    stamp: str,
    index_concepts: list[dict[str, Any]],
) -> str:
    """Human-readable backlinks from ``related_slugs`` edges."""
    slug_set = {c["slug"] for c in index_concepts}
    linked_from: dict[str, list[str]] = defaultdict(list)
    for c in index_concepts:
        s = c["slug"]
        for r in c.get("related_slugs") or []:
            if isinstance(r, str) and r in slug_set and r != s:
                linked_from[r].append(s)
    lines = [
        "# Backlinks",
        "",
        f"_Auto-generated by crate compile --wiki-graph at {stamp}._",
        "",
        "For each concept slug: **outgoing** (`related_slugs` from the model) "
        "and **incoming** (other concepts that point here).",
        "",
    ]
    for c in sorted(index_concepts, key=lambda x: x["slug"]):
        s = c["slug"]
        out = c.get("related_slugs") or []
        inc = sorted(set(linked_from.get(s, [])))
        lines.append(f"## `{s}`")
        lines.append("")
        if out:
            lines.append(f"- **Outgoing:** {', '.join(f'`{x}`' for x in out)}")
        else:
            lines.append("- **Outgoing:** _(none)_")
        if inc:
            lines.append(f"- **Incoming:** {', '.join(f'`{x}`' for x in inc)}")
        else:
            lines.append("- **Incoming:** _(none)_")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _strip_front_matter_for_body(text: str) -> str:
    if not text.startswith("---"):
        return text
    lines = text.splitlines()
    if len(lines) < 2 or lines[0].strip() != "---":
        return text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join(lines[i + 1 :])
    return text


def _first_paragraph_excerpt(path: Path, *, max_chars: int = 220) -> str:
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "_(unreadable)_"
    body = _strip_front_matter_for_body(raw).strip()
    if not body:
        return "_(empty body)_"
    para = body.split("\n\n", 1)[0].replace("\n", " ").strip()
    if len(para) > max_chars:
        return para[: max_chars - 1] + "…"
    return para


def _render_catalog_md(
    stamp: str,
    index_concepts: list[dict[str, Any]],
    ctx: VaultContext,
) -> str:
    """Catalog: title + first-paragraph excerpt per concept (read from disk)."""
    lines = [
        "# Catalog",
        "",
        f"_Auto-generated by `crate compile --wiki-graph` at {stamp}. "
        "One row per concept in `meta/wiki_index.json`._",
        "",
        "| Slug | Title | Excerpt |",
        "|------|-------|---------|",
    ]
    for c in sorted(index_concepts, key=lambda x: str(x.get("slug", ""))):
        slug = str(c.get("slug", ""))
        title = str(c.get("title", slug)).replace("|", "\\|")
        path_s = c.get("path")
        rel = path_s if isinstance(path_s, str) else f"wiki/concepts/{slug}.md"
        p = ctx.root / rel
        ex = _first_paragraph_excerpt(p).replace("|", "\\|")
        lines.append(f"| `{slug}` | {title} | {ex} |")
    lines.append("")
    return "\n".join(lines)


def _render_wiki_index_md(
    stamp: str,
    index_concepts: list[dict[str, Any]],
    raw_sources: list[str],
) -> str:
    """Human-readable hub page under ``wiki/_index/INDEX.md``."""
    lines = [
        "# Wiki index",
        "",
        f"_Auto-generated by crate compile --wiki-graph at {stamp}._",
        "",
        "## Navigation",
        "",
        "- [TOPICS](TOPICS.md) — theme list",
        "- [RECENT](RECENT.md) — recent activity",
        "- [LOG](LOG.md) — append-only activity (after first `crate` event)",
    ]
    if index_concepts:
        lines.extend(
            [
                "- [CATALOG](CATALOG.md) — full concept list + excerpts",
                "- [BACKLINKS](BACKLINKS.md) — concept graph (`related_slugs`)",
                "- [BODYGRAPH](BODYGRAPH.md) — prose link graph "
                "(run `crate wiki graph --md`)",
            ]
        )
    lines.extend(
        [
            "",
            "- [Machine index JSON](../../meta/wiki_index.json) — for scripts / agents",
            "",
        ]
    )
    if index_concepts:
        lines.extend(["## Concepts", ""])
        for c in sorted(index_concepts, key=lambda x: x["slug"]):
            title = str(c.get("title", c["slug"]))
            slug = c["slug"]
            lines.append(f"- [{title}](concepts/{slug}.md)")
        lines.append("")
    lines.extend(["## Raw sources (this compile)", ""])
    if raw_sources:
        for rs in raw_sources:
            lines.append(f"- `{rs}`")
    else:
        lines.append("- _(none)_")
    lines.append("")
    return "\n".join(lines)


def _atomic_write_text(path: Path, content: str, root: Path) -> None:
    ctx = VaultContext(root=root)
    path = ctx.validate_under_vault(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)


def _fallback_single_note(
    ctx: VaultContext,
    paths: list[Path],
    current_all: list[Path],
    text: str,
    model_name: str,
) -> CompileResult:
    """Write a single compile note when JSON parse fails."""
    wiki_notes = ctx.wiki_dir() / "notes"
    wiki_notes.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    slug = "multi"
    if len(paths) == 1:
        slug = re.sub(
            r"[^a-zA-Z0-9._-]+",
            "-",
            paths[0].relative_to(ctx.root).as_posix(),
        )[:40]
    out = wiki_notes / f"compile-{stamp}-{slug}.md"
    out = ctx.validate_under_vault(out)
    source_lines = (
        "\n".join(f"  - path: {p.relative_to(ctx.root).as_posix()!r}" for p in paths)
        if paths
        else "  []"
    )
    front = f"""---
title: "Compile run {stamp}"
kind: compile_run
sources:
{source_lines}
model: {model_name!r}
wiki_graph_fallback: true
created: {datetime.now(timezone.utc).isoformat()}
---

"""
    full_body = front + text + "\n"
    tmp = out.with_name(out.name + ".tmp")
    tmp.write_text(full_body, encoding="utf-8")
    os.replace(tmp, out)
    merge_save_raw_fingerprints(ctx, fingerprints_for_paths(current_all, ctx.root))
    return CompileResult(output_path=out, skipped=False)


def run_wiki_graph_compile(
    ctx: VaultContext,
    paths: list[Path],
    current_all: list[Path],
    *,
    eff_max_chars: int,
    client: OpenAI | None = None,
    model: str | None = None,
    config: DeepSeekConfig | None = None,
    client_factory: Callable[[], tuple[OpenAI, str]] | None = None,
) -> CompileResult:
    """Call LLM for JSON wiki graph; write concept pages and meta/wiki_index.json."""
    user_content = build_compile_prompt(ctx, paths, max_chars_per_file=eff_max_chars)
    user_content = truncate_prompt_for_purpose(user_content, "compile")
    pfile = _prompt_file_path()
    try:
        wiki_prompt = pfile.read_text(encoding="utf-8")
    except OSError:
        wiki_prompt = 'Respond with JSON only: {"version":1,"concepts":[]}'

    system = (
        "You are a structured wiki compiler. Follow the instructions exactly. "
        "Output valid JSON only.\n\n" + wiki_prompt
    )

    if client_factory is not None:
        client_used, model_name = client_factory()
    elif client is not None:
        if model is None:
            raise ValueError("model is required when client is passed")
        client_used = client
        model_name = model
    else:
        cfg = config or load_deepseek_config(purpose="compile")
        client_used, model_name = build_openai_client(cfg)

    resp = client_used.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user_content},
        ],
        temperature=0.2,
        **chat_extra_kwargs_for_purpose("compile"),
    )
    raw_text = (resp.choices[0].message.content or "").strip()

    try:
        data = extract_json_object(raw_text)
    except (json.JSONDecodeError, ValueError) as exc:
        msg = (
            f"wiki-graph: JSON parse failed ({exc}); "
            "falling back to plain compile note."
        )
        print(msg, file=sys.stderr)
        return _fallback_single_note(ctx, paths, current_all, raw_text, model_name)

    if not isinstance(data, dict) or data.get("version") != 1:
        print("wiki-graph: invalid JSON version; falling back.", file=sys.stderr)
        return _fallback_single_note(ctx, paths, current_all, raw_text, model_name)

    concepts = data.get("concepts")
    if not isinstance(concepts, list):
        concepts = []

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    (ctx.wiki_dir() / "concepts").mkdir(parents=True, exist_ok=True)

    index_concepts: list[dict[str, Any]] = []
    seen_slugs: set[str] = set()

    for c in concepts:
        if not isinstance(c, dict):
            continue
        slug_raw = str(c.get("slug", "page"))
        slug = sanitize_slug(slug_raw)
        if slug in seen_slugs:
            slug = f"{slug}-{len(seen_slugs)}"
        seen_slugs.add(slug)
        title = str(c.get("title", slug)).strip() or slug
        body = str(c.get("body", "(empty)")).strip()
        rel = f"wiki/concepts/{slug}.md"
        sources = c.get("sources")
        if not isinstance(sources, list):
            sources = []
        rel_raw = c.get("related_slugs")
        if not isinstance(rel_raw, list):
            rel_raw = []
        rel_slugs: list[str] = []
        for x in rel_raw:
            if not isinstance(x, str):
                continue
            rs = sanitize_slug(x)
            if rs and rs not in rel_slugs:
                rel_slugs.append(rs)

        def _collect_slug_field(raw_key: str) -> list[str]:
            raw = c.get(raw_key)
            if not isinstance(raw, list):
                return []
            out: list[str] = []
            for x in raw:
                if not isinstance(x, str):
                    continue
                s = sanitize_slug(x)
                if s and s not in out:
                    out.append(s)
            return out

        cf_slugs = _collect_slug_field("conflicts_with_slugs")
        sup_slugs = _collect_slug_field("supersedes_slugs")

        def _slug_yaml(key: str, slugs: list[str]) -> str:
            if not slugs:
                return ""
            return f"{key}:\n" + "\n".join(f"  - {json.dumps(s)}" for s in slugs) + "\n"

        src_lines = "\n".join(f"  - path: {s!r}" for s in sources if isinstance(s, str))
        rel_yaml = _slug_yaml("related_slugs", rel_slugs)
        cf_yaml = _slug_yaml("conflicts_with_slugs", cf_slugs)
        sup_yaml = _slug_yaml("supersedes_slugs", sup_slugs)
        front = f"""---
title: {json.dumps(title)}
kind: concept
crate_kind: concept
slug: {json.dumps(slug)}
tags:
  - crate/concept
sources:
{src_lines if src_lines else "  []"}
{rel_yaml}{cf_yaml}{sup_yaml}model: {model_name!r}
updated: {datetime.now(timezone.utc).isoformat()}
compile_stamp: {stamp!r}
---

"""
        out_path = ctx.root / "wiki" / "concepts" / f"{slug}.md"
        _atomic_write_text(out_path, front + body + "\n", ctx.root)
        index_concepts.append(
            {
                "slug": slug,
                "path": rel,
                "title": title,
                "sources": [s for s in sources if isinstance(s, str)],
                "related_slugs": rel_slugs,
                "conflicts_with_slugs": cf_slugs,
                "supersedes_slugs": sup_slugs,
            }
        )

    raw_sources = [p.relative_to(ctx.root).as_posix() for p in paths]
    touched = [c["slug"] for c in index_concepts]
    wiki_index: dict[str, Any] = {
        "version": 1,
        "generated": datetime.now(timezone.utc).isoformat(),
        "model": model_name,
        "compile_stamp": stamp,
        "raw_sources": raw_sources,
        "touched_slugs": touched,
        "concepts": index_concepts,
    }
    meta = ctx.meta_dir()
    meta.mkdir(parents=True, exist_ok=True)
    idx_path = meta / WIKI_INDEX_FILENAME
    _atomic_write_text(
        idx_path,
        json.dumps(wiki_index, ensure_ascii=False, indent=2) + "\n",
        ctx.root,
    )
    last_payload: dict[str, Any] = {
        "version": 1,
        "compile_stamp": stamp,
        "model": model_name,
        "touched_slugs": touched,
        "raw_sources": raw_sources,
    }
    _atomic_write_text(
        meta / COMPILE_WIKI_LAST_FILENAME,
        json.dumps(last_payload, ensure_ascii=False, indent=2) + "\n",
        ctx.root,
    )

    if index_concepts:
        bl_path = ctx.wiki_dir() / "_index" / "BACKLINKS.md"
        _atomic_write_text(
            bl_path,
            _render_backlinks_md(stamp, index_concepts),
            ctx.root,
        )

    topics_md = data.get("topics_markdown")
    if isinstance(topics_md, str) and topics_md.strip():
        topics_path = ctx.wiki_dir() / "_index" / "TOPICS.md"
        _atomic_write_text(
            topics_path,
            f"# 主题索引\n\n"
            f"_Auto-generated by crate compile --wiki-graph at {stamp}._\n\n"
            + topics_md.strip()
            + "\n",
            ctx.root,
        )

    _atomic_write_text(
        ctx.wiki_dir() / "_index" / "INDEX.md",
        _render_wiki_index_md(stamp, index_concepts, raw_sources),
        ctx.root,
    )

    if index_concepts:
        _atomic_write_text(
            ctx.wiki_dir() / "_index" / "CATALOG.md",
            _render_catalog_md(stamp, index_concepts, ctx),
            ctx.root,
        )

    primary_out: Path
    syn = data.get("synthesis_note")
    if isinstance(syn, str) and syn.strip():
        wiki_notes = ctx.wiki_dir() / "notes"
        wiki_notes.mkdir(parents=True, exist_ok=True)
        syn_path = wiki_notes / f"compile-{stamp}-wiki.md"
        syn_path = ctx.validate_under_vault(syn_path)
        src_lines = "\n".join(
            f"  - path: {p.relative_to(ctx.root).as_posix()!r}" for p in paths
        )
        front = f"""---
title: "Compile wiki {stamp}"
kind: compile_run
sources:
{src_lines if src_lines else "  []"}
model: {model_name!r}
wiki_graph: true
created: {datetime.now(timezone.utc).isoformat()}
---

"""
        _atomic_write_text(syn_path, front + syn.strip() + "\n", ctx.root)
        primary_out = syn_path
    elif index_concepts:
        primary_out = ctx.root / index_concepts[0]["path"]
    else:
        primary_out = idx_path

    merge_save_raw_fingerprints(ctx, fingerprints_for_paths(current_all, ctx.root))
    return CompileResult(output_path=primary_out, skipped=False)
