"""Wiki body link graph: markdown + wikilinks in prose -> JSON + optional BODYGRAPH."""

from __future__ import annotations

import json
import os
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from crate.lint_wiki import iter_wiki_outgoing_edges
from crate.vault_paths import VaultContext, VaultPathError

WIKI_BODY_GRAPH_FILENAME = "wiki_body_graph.json"

__all__ = [
    "WIKI_BODY_GRAPH_FILENAME",
    "build_wiki_body_graph",
    "write_wiki_body_graph",
    "atomic_write_text_under_vault",
]


def atomic_write_text_under_vault(path: Path, content: str, root: Path) -> None:
    """Write UTF-8 text via ``*.tmp`` + ``os.replace`` (path under ``root``)."""
    ctx = VaultContext(root=root)
    path = ctx.validate_under_vault(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)


def _list_wiki_markdown_files(
    ctx: VaultContext,
    *,
    include_ephemeral: bool,
    include_outputs: bool,
) -> list[str]:
    wiki = ctx.wiki_dir()
    if not wiki.is_dir():
        return []
    out: list[str] = []
    for path in sorted(wiki.rglob("*.md")):
        if not path.is_file():
            continue
        try:
            ctx.validate_under_vault(path)
        except VaultPathError:
            continue
        rel_parts = path.relative_to(ctx.root).parts
        if not include_ephemeral and "_ephemeral" in rel_parts:
            continue
        rel = path.relative_to(ctx.root).as_posix()
        if not include_outputs and rel.startswith("wiki/outputs/"):
            continue
        out.append(rel)
    return out


def build_wiki_body_graph(
    ctx: VaultContext,
    *,
    include_ephemeral: bool = False,
    include_outputs: bool = False,
) -> dict[str, Any]:
    """Build ``wiki_body_graph`` payload (nodes + edges from prose links)."""
    wiki_files = _list_wiki_markdown_files(
        ctx,
        include_ephemeral=include_ephemeral,
        include_outputs=include_outputs,
    )
    wiki_set = set(wiki_files)
    nodes = [{"path": p} for p in sorted(wiki_files)]
    edges: list[dict[str, Any]] = []
    for src in wiki_files:
        src_path = ctx.root / src
        for e in iter_wiki_outgoing_edges(src_path, ctx):
            if e.target_rel not in wiki_set:
                continue
            edges.append(
                {
                    "from": src,
                    "to": e.target_rel,
                    "kind": e.kind,
                    "line": e.line,
                }
            )
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return {
        "version": 1,
        "generated_at": stamp,
        "nodes": nodes,
        "edges": edges,
    }


def _render_bodygraph_md(payload: dict[str, Any]) -> str:
    """Human-readable hub-degree table + note vs BACKLINKS.md."""
    stamp = str(payload.get("generated_at", ""))
    edges = payload.get("edges")
    if not isinstance(edges, list):
        edges = []
    out_deg: Counter[str] = Counter()
    in_deg: Counter[str] = Counter()
    for e in edges:
        if not isinstance(e, dict):
            continue
        f = e.get("from")
        t = e.get("to")
        if isinstance(f, str) and isinstance(t, str):
            out_deg[f] += 1
            in_deg[t] += 1
    lines = [
        "# Body link graph",
        "",
        f"_Auto-generated by `crate wiki graph --md` at {stamp}._",
        "",
        "These edges come from **markdown links** and **[[wikilinks]]** in wiki prose "
        "(fenced code blocks excluded). For the multi-page compile graph built from "
        "model JSON (`related_slugs`), see [BACKLINKS](BACKLINKS.md).",
        "",
        "| Path | Out-degree | In-degree |",
        "|------|------------|-----------|",
    ]
    node_paths: list[str] = []
    for n in payload.get("nodes", []):
        if isinstance(n, dict) and isinstance(n.get("path"), str):
            node_paths.append(n["path"])
    paths = sorted(set(out_deg) | set(in_deg) | set(node_paths))
    if not paths:
        paths = sorted(node_paths)
    for p in sorted(paths):
        label = p.replace("|", "\\|")
        lines.append(f"| `{label}` | {out_deg.get(p, 0)} | {in_deg.get(p, 0)} |")
    lines.append("")
    return "\n".join(lines)


def write_wiki_body_graph(
    ctx: VaultContext,
    *,
    include_ephemeral: bool = False,
    include_outputs: bool = False,
    write_md: bool = False,
) -> tuple[Path, Path | None]:
    """
    Write ``meta/wiki_body_graph.json`` and optionally ``wiki/_index/BODYGRAPH.md``.

    Returns ``(json_path, md_path_or_none)``.
    """
    payload = build_wiki_body_graph(
        ctx,
        include_ephemeral=include_ephemeral,
        include_outputs=include_outputs,
    )
    meta = ctx.meta_dir()
    meta.mkdir(parents=True, exist_ok=True)
    json_path = meta / WIKI_BODY_GRAPH_FILENAME
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    atomic_write_text_under_vault(json_path, text, ctx.root)

    md_path: Path | None = None
    if write_md:
        md_path = ctx.wiki_dir() / "_index" / "BODYGRAPH.md"
        md_path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text_under_vault(md_path, _render_bodygraph_md(payload), ctx.root)
    return json_path, md_path
